import React from "react";
import { Metadata } from "next";
import ReportForm from "@/src/app/(routes)/report/ReportForm";

export const metadata: Metadata = {
	title: "CMReport",
	description: "Generated by create next app",
};

export default function ReportPage() {
	return <ReportForm />;
}
