import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "./_components/common/AuthProvider";
import ThemeRegistry from "./_components/ThemeRegistry/ThemeRegistry";
import ReduxProvider from "./_components/common/ReduxProvider";
import IntlProviders from "./_components/common/IntlProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body suppressHydrationWarning={true} className={inter.className}>
				<ReduxProvider>
					<IntlProviders>
						<AuthProvider>
							<ThemeRegistry>{children}</ThemeRegistry>
						</AuthProvider>
					</IntlProviders>
				</ReduxProvider>
			</body>
		</html>
	);
}
